name = "api-quota"
main = "src/index.ts"
compatibility_date = "2024-05-29"

[[durable_objects.bindings]]
name = "API_QUOTA"
class_name = "APIQuota"

[[migrations]]
tag = "v1"
new_classes = ["APIQuota"]

[observability]
enabled = true